version: '3.8'

networks:
  stubnet:
    driver: bridge

services:
  postgres:
    image: "pgvector/pgvector:pg16"
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=personal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - stubnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d personal" ]
      interval: 5s
      timeout: 2s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"           # Access from host at localhost:5050
    networks:
      - stubnet
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"       # Access from host at localhost:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - stubnet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"         # Access from host at localhost:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - stubnet

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"         # Access from host at localhost:6379
    networks:
      - stubnet

volumes:
  pgadmin_data:
  postgres_data:
  mongo_data:
